[package]
name = "bevy-gravity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
bevy_egui = "0.24.0"
bevy_mod_picking = { version = "0.17.0", features=["selection"] }
bevy_prototype_lyon = "0.10.0"